import type { InventoryPlayer } from "./storage"

export type BasePlayer = Omit<InventoryPlayer, "id"> & {
  inPacks?: boolean
}

export type PackType = "bronze" | "gold" | "elite"

export const players: BasePlayer[] = [
  {
    baseId: "haaland",
    name: "Haaland",
    rating: 91,
    position: "ST",
    nationFlag: "/flags/norway.png",
    clubLogo: "/clubs/man_city.svg",
    cardImage: "/cards/Haaland.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
    stats: {
          pace: 86,
          shooting: 91,
          passing: 70,
          dribbling: 80,
          defending: 45,
          physical: 88,
        },
  },
  {
    baseId: "debruyne",
    name: "De Bruyne",
    rating: 90,
    position: "CM",
    nationFlag: "/flags/belgium.png",
    clubLogo: "/clubs/man_city.svg",
    cardImage: "/cards/debruyne.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
    stats: {
          pace: 66,
          shooting: 83,
          passing: 92,
          dribbling: 84,
          defending: 65,
          physical: 72,
        },
  },
  {
    baseId: "foden",
    name: "Foden",
    rating: 88,
    position: "RW",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/man_city.svg",
    cardImage: "/cards/foden.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
    stats: {
          pace: 81,
          shooting: 88,
          passing: 75,
          dribbling: 84,
          defending: 51,
          physical: 83,
        },
  },
  {
    baseId: "saka",
    name: "Saka",
    rating: 89,
    position: "RW",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/arsenal.svg",
    cardImage: "/cards/saka.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
    stats: {
          pace: 84,
          shooting: 82,
          passing: 85,
          dribbling: 88,
          defending: 60,
          physical: 73,
        },
  },
  {
    baseId: "rice",
    name: "Rice",
    rating: 87,
    position: "CM",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/arsenal.svg",
    cardImage: "/cards/rice.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "vandijk",
    name: "Van Dijk",
    rating: 89,
    position: "CB",
    nationFlag: "/flags/netherlands.png",
    clubLogo: "/clubs/liverpool.svg",
    cardImage: "/cards/vandijk.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "salah",
    name: "Salah",
    rating: 90,
    position: "RW",
    nationFlag: "/flags/egypt.svg",
    clubLogo: "/clubs/liverpool.svg",
    cardImage: "/cards/salah.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "palmer",
    name: "Palmer",
    rating: 86,
    position: "CAM",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/chelsea.svg",
    cardImage: "/cards/palmer.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "bruno",
    name: "Bruno Fernandes",
    rating: 86,
    position: "CAM",
    nationFlag: "/flags/portugal.svg",
    clubLogo: "/clubs/man_united.svg",
    cardImage: "/cards/bruno.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "bellingham",
    name: "Bellingham",
    rating: 90,
    position: "CM",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/Real_Madrid.svg",
    cardImage: "/cards/bellingham.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "vinicius",
    name: "Vinicius Jr",
    rating: 90,
    position: "LW",
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/Real_Madrid.svg",
    cardImage: "/cards/vinicius.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "rodrygo",
    name: "Rodrygo",
    rating: 87,
    position: "RW",
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/Real_Madrid.svg",
    cardImage: "/cards/rodrygo.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "lewandowski",
    name: "Lewandowski",
    rating: 89,
    position: "ST",
    nationFlag: "/flags/poland.svg",
    clubLogo: "/clubs/barcelona.svg",
    cardImage: "/cards/lewandowski.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "pedri",
    name: "Pedri",
    rating: 86,
    position: "CM",
    nationFlag: "/flags/spain.svg",
    clubLogo: "/clubs/barcelona.svg",
    cardImage: "/cards/pedri.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "kane",
    name: "Kane",
    rating: 90,
    position: "ST",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/bayern.svg",
    cardImage: "/cards/kane.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "musiala",
    name: "Musiala",
    rating: 88,
    position: "CAM",
    nationFlag: "/flags/germany.svg",
    clubLogo: "/clubs/bayern.svg",
    cardImage: "/cards/musiala.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "wirtz",
    name: "Wirtz",
    rating: 87,
    position: "CAM",
    nationFlag: "/flags/germany.svg",
    clubLogo: "/clubs/leverkusen.png",
    cardImage: "/cards/wirtz.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "lautaro",
    name: "Lautaro",
    rating: 89,
    position: "ST",
    nationFlag: "/flags/argentina.png",
    clubLogo: "/clubs/inter.png",
    cardImage: "/cards/lautaro.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "leao",
    name: "Leao",
    rating: 87,
    position: "LW",
    nationFlag: "/flags/portugal.png",
    clubLogo: "/clubs/milan.png",
    cardImage: "/cards/leao.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "mbappe",
    name: "Mbappe",
    rating: 91,
    position: "ST",
    nationFlag: "/flags/france.svg",
    clubLogo: "/clubs/psg.svg",
    cardImage: "/cards/mbappe.png",
    rarity: "gold",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "dembele",
    name: "Dembele",
    rating: 86,
    position: "RW",
    nationFlag: "/flags/france.svg",
    clubLogo: "/clubs/psg.svg",
    cardImage: "/cards/dembele.png",
    rarity: "gold",
    walkoutType: "normal",
    inPacks: true,
  },
  {
    baseId: "ronaldo_icon",
    name: "Ronaldo",
    rating: 94,
    position: "ST",
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/ronaldo.png",
    rarity: "elite",
    walkoutType: "big",
    inPacks: true,
  },
  {
    baseId: "zidane_icon",
    name: "Zidane",
    rating: 94,
    position: "CAM",
    nationFlag: "/flags/france.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/zidane.png",
    rarity: "elite",
    walkoutType: "big",
    inPacks: true,

  },
  {
    baseId: "neymar",
    name: "Neymar",
    rating: 96,
    position: "CAM",
    altPositions: ["LW"],
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/santos.png",
    cardImage: "/cards/neymar_founder.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 94,
      shooting: 89,
      passing: 91,
      dribbling: 98,
      defending: 40,
      physical: 68,
    }
  },
  {
    baseId: "neuer",
    name: "Neuer",
    rating: 96,
    position: "GK",
    nationFlag: "/flags/germany.svg",
    clubLogo: "/clubs/bayern.svg",
    cardImage: "/cards/neuer_era.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 63,
      shooting: 1,
      passing: 91,
      dribbling: 1,
      defending: 1,
      physical: 1,
      diving: 95,
      handling: 93,
      kicking: 97,
      reflexes: 95,
      speed: 63,
      positioning: 96,
    }
  },
  {
    baseId: "bale",
    name: "Bale",
    rating: 97,
    position: "LB",
    nationFlag: "/flags/wales.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/bale_lb.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 98,
      shooting: 87,
      passing: 89,
      dribbling: 90,
      defending: 86,
      physical: 89,
    }
  },
  {
    baseId: "kroos",
    name: "Kroos",
    rating: 95,
    position: "CM",
    nationFlag: "/flags/germany.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/kroos_era.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 70,
      shooting: 87,
      passing: 97,
      dribbling: 86,
      defending: 72,
      physical: 78,
    }
  },
  {
    baseId: "pirlo",
    name: "Pirlo",
    rating: 96,
    position: "CM",
    nationFlag: "/flags/italy.png",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/pirlo_founder.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 72,
      shooting: 85,
      passing: 99,
      dribbling: 90,
      defending: 68,
      physical: 74,
    }
  },
  {
    baseId: "campbell",
    name: "Campbell",
    rating: 95,
    position: "CB",
    nationFlag: "/flags/england.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/campbell_founder.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 80,
      shooting: 45,
      passing: 68,
      dribbling: 62,
      defending: 96,
      physical: 95,
    }
  },
  {
    baseId: "cafu",
    name: "Cafu",
    rating: 97,
    position: "RB",
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/cafu_carnival.jpg",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 96,
      shooting: 72,
      passing: 90,
      dribbling: 91,
      defending: 91,
      physical: 87,
    }
  },
  {
    baseId: "gullit_95",
    name: "Gullit",
    rating: 95,
    position: "ST",
    altPositions: ["CAM", "CM", "CDM", "RW", "LW", "CB"],
    nationFlag: "/flags/netherlands.png",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/gullit_95.jpg",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 87,
      shooting: 90,
      passing: 90,
      dribbling: 90,
      defending: 78,
      physical: 92,
    }
  },
  {
    baseId: "vieira",
    name: "Vieira",
    rating: 97,
    position: "CDM",
    altPositions: ["CM"],
    nationFlag: "/flags/france.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/vieira.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 87,
      shooting: 80,
      passing: 88,
      dribbling: 85,
      defending: 98,
      physical: 97,
    }
  },
  {
    baseId: "r9_92",
    name: "Ronaldo",
    rating: 92,
    position: "ST",
    nationFlag: "/flags/brazil.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/r9_92.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 89,
      shooting: 90,
      passing: 78,
      dribbling: 92,
      defending: 45,
      physical: 80,
    }
  },

  {
    baseId: "torres_99",
    name: "FernandoTorres",
    rating: 99,
    position: "ST",
    altPositions: ["RW"],
    nationFlag: "/flags/spain.png",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/torres_99.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: false,
    stats: {
      pace: 99,
      shooting: 92,
      passing: 74,
      dribbling: 96,
      defending: 45,
      physical: 87,
    }
  },
  {
    baseId: "ruben_94",
    name: "Rúben Dias",
    rating: 94,
    position: "CB",
    nationFlag: "/flags/portugal.png",
    clubLogo: "/clubs/man_city.svg",
    cardImage: "/cards/ruben_94.jpg",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 75,
      shooting: 47,
      passing: 82,
      dribbling: 75,
      defending: 95,
      physical: 93,
    }
  },
  {
    baseId: "ballack_100",
    name: "Michael Ballack",
    rating: 100,
    position: "CM",
    altPositions: ["CDM"],
    nationFlag: "/flags/germany.svg",
    clubLogo: "/clubs/icon.png",
    cardImage: "/cards/ballack_100.png",
    rarity: "icon",
    walkoutType: "big",
    inPacks: true,
    stats: {
      pace: 91,
      shooting: 99,
      passing: 99,
      dribbling: 95,
      defending: 93,
      physical: 99,
    }
  },
  {
      baseId: "gullit_evo_99",
      name: "Gullit",
      rating: 99,
      position: "CM",
      altPositions: ["CDM", "CAM", "CB", "LB", "RB", "RW", "LW"],
      nationFlag: "/flags/netherlands.png",
      clubLogo: "/clubs/icon.png",
      cardImage: "/cards/gullit_99.png",
      rarity: "icon",
      walkoutType: "big",
      inPacks: false,
      stats: {
        pace: 99,
        shooting: 96,
        passing: 99,
        dribbling: 98,
        defending: 92,
        physical: 96,
      },
    },
    {
      baseId: "r9_100",
      name: "Ronaldo",
      rating: 100,
      position: "ST",
      nationFlag: "/flags/brazil.svg",
      clubLogo: "/clubs/icon.png",
      cardImage: "/cards/r9_100.png",
      rarity: "icon",
      walkoutType: "big",
      inPacks: false,
      stats: {
        pace: 100,
        shooting: 100,
        passing: 84,
        dribbling: 100,
        defending: 45,
        physical: 89,
      },
    },


]

export const packs: Record<
  PackType,
  {
    name: string
    price: number
    odds: {
      gold: number
      elite: number
      icon: number
    }
  }
> = {
  bronze: {
    name: "icon pack",
    price: 100000,
    odds: {
      gold: 0,
      elite: 0,
      icon: 1,
    },
  },
  gold: {
    name: "Gold Pack",
    price: 10000,
    odds: {
      gold: 0.8,
      elite: 0.2,
      icon: 0,
    },
  },
  elite: {
    name: "Elite Pack",
    price: 20000,
    odds: {
      gold: 0.599,
      elite: 0.4,
      icon: 0.001,
    },
  },
}

export function rollRarity(packType: PackType): "gold" | "elite" | "icon" {
  const r = Math.random()
  const odds = packs[packType].odds

  if (r < odds.icon) return "icon"
  if (r < odds.icon + odds.elite) return "elite"
  return "gold"
}

export function getRandomPlayerForPack(packType: PackType): BasePlayer {
  const rarity = rollRarity(packType)

  const pool = players.filter(
    (player) =>
      player.rarity === rarity &&
      player.inPacks !== false // 👈 THIS FIX
  )

  if (pool.length === 0) {
    // fallback to ANY packable player
    const fallback = players.filter((p) => p.inPacks !== false)
    return fallback[Math.floor(Math.random() * fallback.length)]
  }

  return pool[Math.floor(Math.random() * pool.length)]
}